/** Shared manufacturer list for Watch.brand and DiscountCode.eligibleBrands. Keep in sync with `hijo/schemaTypes/watchBrands.ts`. */
export const WATCH_BRAND_OPTIONS = [
  { title: "Casio", value: "casio" },
  { title: "Citizen", value: "citizen" },
  { title: "Orient", value: "orient" },
  { title: "Seiko", value: "seiko" },
  { title: "Audemars Piguet", value: "audemars-piguet" },
  { title: "Breitling", value: "breitling" },
  { title: "Cartier", value: "cartier" },
  { title: "F.P. Journe", value: "fp-journe" },
  { title: "Franck Muller", value: "franck-muller" },
  { title: "Girard-Perregaux", value: "girard-perregaux" },
  { title: "Jacob & Co.", value: "jacob-co" },
  { title: "Longines", value: "longines" },
  { title: "Omega", value: "omega" },
  { title: "Patek Philippe", value: "patek-philippe" },
  { title: "Richard Mille", value: "richard-mille" },
  { title: "Rolex", value: "rolex" },
  { title: "Tissot", value: "tissot" },
  { title: "Tudor", value: "tudor" },
  { title: "Vacheron Constantin", value: "vacheron-constantin" },
  { title: "Other", value: "other" },
] as const;
